# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kaX-HH2zvu8QmjUyTR-GYqUENJk6eHXz
"""

import pandas as pd
import numpy as np
import matplotlib as mlp
from google.colab import files
uploaded= files.upload()

datafile=pd.read_csv("Salary_Data.csv")



datafile

datafile.describe()

x=datafile.iloc[:,:-1].values
y=datafile.iloc[:,1].values
from sklearn.model_selection import train_test_split
x_train,x_test , y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

y_pred=regressor.predict(x_test)
y_pred



mlp.scatter(x_train,y_train,color="red")
mlp.plot(x_train, regressor.predict(x_train),color="blue")

import matplotlib.pyplot as mlp

mlp.scatter(x_train,y_train,color="red")
mlp.plot(x_train, regressor.predict(x_train),color="blue")

mlp.tittle("salary vs experirnce(training set)")